Feat/comment model
platanus/fdbk2 pull request #1
Opened 2023-08-22 13:55 UTC by manarea

### Contexto
​​Se realizaron modificaciones a los modelos para poder dar soporte a los comentarios dentro del feedback entregado y a su vez se vincularon estos últimos en ActiveAdmin para que pudieran ser visualizadas.

Además, se modificó el script usado para poblar la base de datos para agregar automáticamente 2 comentarios random a cada sesión de feedback.
### Qué se esta haciendo
​​Se está implementando la lógica de los comentarios en las sesiones de feedback para poder pasar a desarrollar la vista correspondiente.
#### En particular hay que revisar
​​Son dos cosas las importantes:

Los modelos modificados y sus relaciones,
El nuevo módulo para ActiveAdmin

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)
![262175550-c5a7e8d1-6f27-4b42-9918-b9a2ccc62389](https://github.com/platanus/fdbk2/assets/48288027/7623fc9c-0779-4729-ba54-92f38c5c9af9)
![262175580-27183dec-ff92-4717-8024-ba607faa756b](https://github.com/platanus/fdbk2/assets/48288027/85764c68-3e99-41be-959b-d67ddc7e77a7)

2023-08-22 13:56 UTC, monkeyci commented on app/models/comment.rb
> +    belongs_to :feedback_session
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/IndentationWidth: Use 2 (not 4) spaces for indentation.

2023-08-22 13:56 UTC, monkeyci commented on app/models/feedback_session.rb
> +  has_many :comments
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/HasManyOrHasOneDependent: Specify a :dependent option.

2023-08-22 13:56 UTC, monkeyci commented on lib/fake_data_loader.rb
> +            body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: true, random_sentences_to_add: 4)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/LineLength: Line is too long. [107/100]

2023-08-22 13:56 UTC, monkeyci commented on lib/fake_data_loader.rb
> +            body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: true, random_sentences_to_add: 4)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/LineLength: Line is too long. [107/100]

2023-08-22 13:56 UTC, monkeyci commented on lib/fake_data_loader.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end.

2023-08-22 13:56 UTC, monkeyci commented on lib/fake_data_loader.rb
> +end
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/TrailingEmptyLines: Final newline missing.

2023-08-22 14:19 UTC, monkeyci commented on lib/fake_data_loader.rb
> +        password: USER_PASSWORD,
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/TrailingCommaInArguments: Avoid comma after the last parameter of a method call.

2023-08-22 14:19 UTC, monkeyci commented on lib/fake_data_loader.rb
> +          receiver: User.where.not(id: user.id).sample,
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/TrailingCommaInArguments: Avoid comma after the last parameter of a method call.

2023-08-22 14:19 UTC, monkeyci commented on lib/fake_data_loader.rb
> +            body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: true, random_sentences_to_add: 4),
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/LineLength: Line is too long. [108/100]

2023-08-22 14:19 UTC, monkeyci commented on lib/fake_data_loader.rb
> +            body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: true, random_sentences_to_add: 4),
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/TrailingCommaInArguments: Avoid comma after the last parameter of a method call.

2023-08-22 14:19 UTC, monkeyci commented on lib/fake_data_loader.rb
> +            body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: true, random_sentences_to_add: 4),
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Layout/LineLength: Line is too long. [108/100]

2023-08-22 14:19 UTC, monkeyci commented on lib/fake_data_loader.rb
> +            body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: true, random_sentences_to_add: 4),
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>[Correctable] Style/TrailingCommaInArguments: Avoid comma after the last parameter of a method call.

2023-08-22 15:23 UTC, ldlsegovia reviewed
Super good! Algunas sugerencias:
- Instala [linter de rubocop ](https://marketplace.visualstudio.com/items?itemName=misogi.ruby-rubocop) para que los errores de estilo no lleguen a tu PR
- Instala plugin de [editor config](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) para que te arregle la indentación. Acá no vi pero en tu otro PR vi problemas de tabs y saltos de línea.
- Para la próxima, los commits en imperativo: https://la-guia.platan.us/setup/configuracion_de_proyectos/git#descripcion

2023-08-22 15:23 UTC, ldlsegovia commented on lib/fake_data_loader.rb
> +        end
Tratá de ser lo más DRY posible. En este caso podés usar el método `create_list` de Factory Bot.

```ruby
create_list(
    :comment,
    2
    feedback_session: session,
    body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: true, random_sentences_to_add: 4)
)
```

2023-08-22 15:23 UTC, ldlsegovia commented on spec/models/comment_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Al menos siempre agrega un test para ver que la factory sea válida Por ej https://github.com/platanus/nest/blob/master/spec/models/meet_url_spec.rb#L5

2023-08-22 15:23 UTC, ldlsegovia commented on spec/factories/comments.rb
> +    feedback_session_id { "" }
Un comentario debería siempre tener una sesión asociada. Por esto mejor poner  `feedback_session` en vez de `feedback_session_id { "" }`. Eso le asignará a la factory una sesión al crearse el comentario

2023-08-22 15:23 UTC, ldlsegovia commented on app/models/comment.rb
> +#  body                :text
quizás sería bueno que agregues una validación de presencia a `body`

2023-08-22 16:49 UTC, difernandez requested changes
Nice, algunos detalles! Y comentario más general: la mayoría de las veces, cuando tenemos que hacer un cambio en un PR debido a un comentario del mono, o una corrección de una review que requiere cambios a algo que hice, no aplicamos los nuevos cambios directo en un nuevo commit. Usamos rebase para aplicar los cambios en el commit en que se introdujo el código que estamos cambiando. [Acá hay un par de links que te pueden servir](https://la-guia.platan.us/setup/configuracion_de_proyectos/git#rebase). La idea detrás de esto es tener un historial de commits limpio, con cambios significativos y atómicos que después sean fáciles de buscar y entender. No es necesario que cambies lo que ya hiciste, pero para que lo tengas en consideración para los cambios que salgan de esta review y futuros PRs!
Y ojo que queda un par de comentarios del mono sin corregir

2023-08-22 16:49 UTC, difernandez commented on app/admin/feedback_sessions.rb
> +    end
si agregar form para una asociación, necesitas dos cosas que faltan acá:
- En el modelo tiene que haber un `accepts_nested_attributes_for :comments, allow_destroy: true`
- Acá en el `permitted_params` se tienen que permitir lo params de la asociación, agregando `comments_attributes: [:body]`

2023-08-22 16:49 UTC, difernandez commented on db/schema.rb
> +
por lo general, recomendaría poner los cambios de schema junto a los cambios de modelo y la migración relación relacionada. No es necesario que un commit sea solo un archivo, la idea es que contenga una cosita atómica de cambios muy relacionados, como en este caso agregar una tabla implica esos tres cambios

2023-08-22 16:49 UTC, difernandez commented on db/migrate/20230821165538_add_comment_to_feedback_session.rb
> +    add_reference :feedback_sessions, :comment, null: true, index: {algorithm: :concurrently}
- siempre que agregues una reference, agrega también la foreign_key
- Dicho eso, esta migración no es necesaria. Con esto estás agregando una referencia en la sesión a 1 comentario, cuando la relación es al revés y ya se está agregando en la otra migración (piensa en reference == belongs_to)

2023-08-22 16:49 UTC, difernandez commented on db/migrate/20230821162525_create_comments.rb
> +      t.bigint :feedback_session_id
- Esto debería ser una reference, no bigint. El reference agrega el index asociado
- Falta agregar la foreign_key
- Relacionado a lo que puso lean: un comentario tiene que pertenecer a una sesión. Le agregaría `null: false`

2023-08-23 18:10 UTC, manarea commented on lib/fake_data_loader.rb
> +        end
Muchas gracias por el feedback en general Leandro! Ahora voy a cambiar las cosas! Esto quedó implementado en código!

2023-08-23 18:16 UTC, manarea commented on spec/factories/comments.rb
> +    feedback_session_id { "" }
Cambiado!

2023-08-23 18:19 UTC, manarea commented on app/models/comment.rb
> +#  body                :text
Agregada la validación!

2023-08-23 18:30 UTC, manarea commented on spec/models/comment_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Agregado el test para validar la factory!

2023-08-23 19:02 UTC, manarea commented on app/admin/feedback_sessions.rb
> +    end
Cambiado!

2023-08-23 19:03 UTC, manarea commented on db/schema.rb
> +
Procedo a hacerle squash!

2023-08-23 19:18 UTC, manarea commented on db/migrate/20230821162525_create_comments.rb
> +      t.bigint :feedback_session_id
Solucionado!

2023-08-23 19:18 UTC, monkeyci commented on lib/fake_data_loader.rb
> +          create_list(:comment, rand(1..5), feedback_session: session, body: Faker::Lorem.paragraph(sentence_count: 2, supplemental: true,
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Layout/LineLength: Line is too long. [138/100]

2023-08-23 19:18 UTC, monkeyci commented on lib/fake_data_loader.rb
> +                                                                                                    random_sentences_to_add: 4))
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Layout/LineLength: Line is too long. [128/100]

2023-08-23 19:19 UTC, manarea commented on db/schema.rb
> +
Creo que ahora debería quedar listo! Agregué todas las cosas relacionadas dentro de un mismo commit!

2023-08-23 19:19 UTC, manarea commented on db/migrate/20230821165538_add_comment_to_feedback_session.rb
> +    add_reference :feedback_sessions, :comment, null: true, index: {algorithm: :concurrently}
Creo que ahora debería quedar listo! Agregué todas las cosas relacionadas dentro de un mismo commit!

2023-08-23 21:12 UTC, difernandez requested changes
Good! dejé un comentario TOC jeje

2023-08-23 21:12 UTC, difernandez commented on app/models/comment.rb
> +  belongs_to :feedback_session
- En la mayoría de los casos, evitamos comentarios, tratamos que el código sea autoexplicativo. Son pocas las excepciones, un ejemplo puede ser cuando se está modificando código de una gema para soportar algo que no se puede hacer por defecto, cosas rebuscadas así
- Por lo general ponemos las asociaciones antes que las validaciones. Hay una regla de linter que las debería haber reordenado, pero creo que no está en el proyecto, ups

2023-08-24 15:13 UTC, manarea commented on app/models/comment.rb
> +  belongs_to :feedback_session
Super, lo arreglo altiro! Muchas gracias!

2023-08-28 12:37 UTC, ldlsegovia approved these changes
👏🏻

2023-08-28 21:38 UTC, difernandez approved these changes
bueena 🎉

2023-08-28 22:58 UTC, merged